<?php
$xmlList = simplexml_load_file("output.xml") or die("Error: Cannot find XML file.");
echo "<link href=\"table.css\" rel=\"stylesheet\" type=\"text/css\">";
echo "<h2>XML Account Results!</h2>";
echo "<table style=\"width:100%\">";
echo "<tr>";
echo "<th>id</th>";
echo "<th>name_english</th>";
echo "<th>name_japanese</th>";
echo "<th>type</th>";
echo "<th>price_buy</th>";
echo "<th>price_sell</th>";
echo "<th>weight</th>";
echo "<th>attack</th>";
echo "<th>defence</th>";
echo "<th>range</th>";
echo "<th>slots</th>";
echo "<th>equip_jobs</th>";
echo "<th>equip_upper</th>";
echo "<th>equip_genders</th>";
echo "<th>equip_locations</th>";
echo "<th>weapon_level</th>";
echo "<th>equip_level</th>";
echo "<th>refineable</th>";
echo "<th>view</th>";
echo "<th>script</th>";
echo "<th>equip_script</th>";
echo "<th>unequip_script</th>";
echo "</tr>";
foreach ($xmlList->account as $user) {
    echo "<tr>";
    echo "<td>".$user->id."</td>";
    echo "<td>".$user->name_english."</td>";
    echo "<td>".$user->name_japanese."</td>";
    echo "<td>".$user->type."</td>";
    echo "<td>".$user->price_buy."</td>";
    echo "<td>".$user->price_sell."</td>";
    echo "<td>".$user->weight."</td>";
    echo "<td>".$user->attack."</td>";
    echo "<td>".$user->defence."</td>";
    echo "<td>".$user->range."</td>";
    echo "<td>".$user->slots."</td>";
    echo "<td>".$user->equip_jobs."</td>";
    echo "<td>".$user->equip_upper."</td>";
    echo "<td>".$user->equip_genders."</td>";
    echo "<td>".$user->equip_locations."</td>";
    echo "<td>".$user->weapon_level."</td>";
    echo "<td>".$user->equip_level."</td>";
    echo "<td>".$user->refineable."</td>";
    echo "<td>".$user->view."</td>";
    echo "<td>".$user->script."</td>";
    echo "<td>".$user->equip_script."</td>";
    echo "<td>".$user->unequip_script."</td>";
    echo "</tr>";
}
echo "</table>";
echo "<br>";
?>